### ISSUE TITLE
Do not raise ArgumentError when assigning a blank value

### ISSUE THREAD

**Issue by koki-sato** [freeletics/array_enum#16]
Looking at [array_enum.rb#L39](https://github.com/freeletics/array_enum/blob/master/lib/array_enum.rb#L39), I think assigning a blank value to ArrayEnum will raise an ArgumentError.

```ruby
class User < ActiveRecord::Base
  extend ArrayEnum

  array_enum favourite_colors: {"red" => 1, "blue" => 2, "green" => 3}
end

user = User.new(favourite_colors: [""]) # raises ArgumentError!
```

However, Rails (ActiveRecord) implementation of Enum do not raise an ArgumentError when assigning a blank value.

https://github.com/rails/rails/blob/v7.0.2.3/activerecord/lib/active_record/enum.rb#L155-L159

I don't want to raise an ArgumentError if the value is blank (I want to validate it with Subset Validator).

**Comment by wesleyeewong** [comment]
Hey @koki-sato what would be a use-case for such behavior?

Is it just for instantiation and before persisting?

**Comment by koki-sato** [comment]
> Is it just for instantiation and before persisting?

Yes!

I expect the following behavior.

```ruby
class User < ActiveRecord::Base
  extend ArrayEnum

  array_enum favourite_colors: {"red" => 1, "blue" => 2, "green" => 3}

  validates :favourite_colors, presence: true, subset: { in: favourite_colors.keys }
end

user = User.new(favourite_colors: [""]) # Do not raise ArgumentError!
user.save # => false
user.errors.messages[:favourite_colors] # Display inclusion validation error message
```

**Comment by khaledm1990** [comment]
@koki-sato Since not many have been asking for such functionality I will close the issue for now 

Feel free to create a PR, if you still see a need for it

**Comment by dgmora** [comment]
This is not the same that rails does. When you assign an invalid value to an array enum, raise doesn't raise but marks the object as invalid.

The docs also state this:

```
CreateUser.new(favourite_colors: ["black"]).valid? # => false
```

But this doesn't seem to apply when you use a setter:

```
CreateUser.new.favourite_colors = ["black"] # => Would raise
```

Rails though raises `ArgumentError` when assigning an invalid enum value in the case it is not an array.
