### ISSUE TITLE
PG::AmbiguousColumn error when multiple tables have an array_enum column with the same name

### ISSUE THREAD

**Issue by itsameandrea** [freeletics/array_enum#17]
Hey folks!

In my project I have three models `lesson.rb`, `lesson_module.rb` and `sequence.rb` that are all using `array_enum` like so

```
array_enum year_levels: {
    year_6: 1,
    year_7: 2,
    year_8: 3,
    year_9: 4,
    year_10: 5,
    year_11: 6,
    year_12: 7,
  }
```

I implemented a bunch of filters in the `lesson.rb` file using scopes

```
scope :filter_by_year_level, -> (year_levels) { with_any_of_year_levels(year_levels) }
scope :filter_by_module, -> (modules) {joins(:lesson_modules).where(lesson_modules: {id: modules})}
scope :filter_by_sequence, -> (sequences) {joins(lesson_modules: [:sequences]).where(lesson_modules: {sequences: { id: sequences}})}
```

If a request comes in and I need to `filter_by_year_level` as well as any of the other two scopes, then I get a `PG::AmbiguousColumn` since there are a grand total of three `year_levels` columns across the three tables.

Any easy way to get around this issue? I suppose we could switch [this](https://github.com/freeletics/array_enum/blob/master/lib/array_enum.rb#L29) with something like

`where("#{table_name}.#{attr_name} #{comparison_operator} ARRAY[:db_values]", db_values: db_values)`

What do you think?

**Comment by khaledm1990** [comment]
@itsameandrea the above mentioned issue has been fixed released in 1.5.0 V
thanks for your input
