### ISSUE TITLE
Empty Array parameter saved despite of default value is set

### ISSUE THREAD

**Issue by Deniz-Iren** [freeletics/array_enum#18]
Greetings,

I have a field with default value is set as below:
```ruby 
t.integer :favourite_colors, array: true, null: false, default: [0]
# model def:
array_enum favourite_colors: {"red" => 1, "blue" => 2, "green" => 3}
```
but when sending parameter as `favourite_colors: []` empty array this results in record being saved with empty array instead of default one.

**Comment by kemalmutlu** [comment]
any news?

**Comment by Deniz-Iren** [comment]
> any news?

Not yet @kemalmutlu

**Comment by wesleyeewong** [comment]
This is expected behavior no?

Empty array does not mean null value so it doesn't get assigned the default value.

Have you tried explicitly setting it to `nil`?

**Comment by Deniz-Iren** [comment]
@wesleyeewong thank you for response,  yes setting it to `nil` does set to default value.
