### ISSUE TITLE
Not working under rails 7.2

### ISSUE THREAD

**Issue by xdmx** [freeletics/array_enum#21]
I'm upgrading an app to rails 7.2 that uses this gem (thank you for it!), but I'm getting a cast error.

I've confirmed it by creating a fresh new rails 7.2 app (`rails new rails72 -d postgresql`), and then go through the readme.

`user.favourite_colors` works, but when I try the scopes `User.with_favourite_colors("red")`, `User.only_with_favourite_colors("red")`, `User.with_any_of_favourite_colors("red")` it blows up with

```
An error occurred when inspecting the object: #<ActiveRecord::StatementInvalid:"PG::UndefinedFunction: ERROR:  operator does not exist: integer[] && text[]\nLINE 1: ...ers\".* FROM \"users\" WHERE (users.favourite_colors && ARRAY[$...
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.">
```

**Comment by guoy-freeletics** [comment]
@xdmx We have released a new version that fixes this issue. Thanks for the report.
