### ISSUE TITLE
Please add CHANGELOG.md file

### ISSUE THREAD

**Issue by tilo** [freeletics/array_enum#25]
there seems to be no CHANGELOG.md file explaining the changes in each new version

**Comment by khaledm1990** [comment]
@tilo Thank you for your feedback;
I completely agree. I'll be adding a changelog file soon, but unfortunately, I don't have the full history of all the changes. For now, I'll include only the most recent updates.

**Comment by khaledm1990** [comment]
The last 2 version changes have been added in by [this](https://github.com/freeletics/array_enum/pull/26) PR
