### ISSUE TITLE
ArgumentError for invalid values to array_enum

### ISSUE THREAD

**Issue by alexanderdavide** [freeletics/array_enum#7]
In my model, I use ArrayEnum like this:
```
class MyModel < ApplicationRecord
  extend ArrayEnum

  array_enum assignables: { ASSIGNABLE1: 1, ASSIGNABLE2: 2 }

  validates :assignables, presence: true
end
```
Now, if I want to create an instance of MyModel using IRB with an invalid value for assignables like this
`MyModel.new(assignables: ["test"])`, an ArgumentError is thrown: `ArgumentError (test is not a valid value for assignables)`.

I expected to receive an error on the model instance which I am able to derive using `.errors`. Is there a way I can achieve that? I have already tried to apply an inclusion validation to the assignables field but without success.

**Comment by wesleyeewong** [comment]
@alexanderdavide 

What we do is we have an `interactor` object that does the validations before creating our `model` object (See the example on the readme).

Another way is to override the setter method, see:
https://github.com/freeletics/array_enum/blob/5f8803dba337ff17d746925f5f5a8bdd3f27fe2c/lib/array_enum.rb#L31-L35

So define your validations like you usually do, then in the model class add:
```
def assignables=(values)
  @assignables = values # or do what you need to do here
end
```

Not pretty workaround unfortunately, but it works.
